package My_Forms;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Nguyễn Văn Khoa
 */
public class ThongTinCuaHang extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.CuaHang cuahang = new My_Classes.CuaHang();
    My_Classes.User member = new My_Classes.User();
    My_Classes.ChungNhan genre = new My_Classes.ChungNhan();
    My_Classes.Func_Class func = new My_Classes.Func_Class();

    public ThongTinCuaHang(int ID_CH) {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(252, 231, 125));
        jPanel1.setBorder(panelHeaderBorder);

        //display image        
        func.displayImage(70, 70, null, "/My_Images/icons8_male_user_100px.png", jLabel_Form_Title);

        //border the image
        Border JlaBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        //display the book infor
        displayMemberInfor(ID_CH);
    }

    //creat a func to display the book infor
    public void displayMemberInfor(int ID_CH) {
        try {
            My_Classes.CuaHang selectedCuaHang = cuahang.getCuaHangById(ID_CH);

            if (selectedCuaHang != null) {
                jLabel_ID.setText("ID Cửa hàng :" + String.valueOf(selectedCuaHang.getId()));
                jLabel_TenCH.setText("Tên Cửa Hàng : "+ selectedCuaHang.getCuaHang()); //
                jLabel_TenChuCH.setText("Chủ Sở Hữu: "+ selectedCuaHang.getTenChuCuaHang()); //
                jLabel_DiaChi.setText("Địa Chỉ : "+selectedCuaHang.getDiaChi());
                jLabel_Hotline.setText("Hotline : "+selectedCuaHang.getHotline());
                jLabel_SoLuong.setText("Số Lượng Chứng Nhận Đã Được Cấp: "+selectedCuaHang.getSLCN());
            } else {
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinCuaHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_TenCH = new javax.swing.JLabel();
        jLabel_DiaChi = new javax.swing.JLabel();
        jLabel_TenChuCH = new javax.swing.JLabel();
        jLabel_Hotline = new javax.swing.JLabel();
        jLabel_SoLuong = new javax.swing.JLabel();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(252, 231, 125));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("THÔNG TIN CỬA HÀNG");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(252, 231, 125));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_ID.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_ID.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_ID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_ID.setText("ID:");
        jLabel_ID.setOpaque(true);

        jLabel_TenCH.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_TenCH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TenCH.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_TenCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_TenCH.setText("Tên Cửa Hàng");
        jLabel_TenCH.setOpaque(true);

        jLabel_DiaChi.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_DiaChi.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_DiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_DiaChi.setText("Địa Chỉ");
        jLabel_DiaChi.setOpaque(true);

        jLabel_TenChuCH.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_TenChuCH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TenChuCH.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_TenChuCH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_TenChuCH.setText("Tên Chủ Cửa Hàng");
        jLabel_TenChuCH.setOpaque(true);

        jLabel_Hotline.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Hotline.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Hotline.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_Hotline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Hotline.setText("Hotline");
        jLabel_Hotline.setOpaque(true);

        jLabel_SoLuong.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_SoLuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_SoLuong.setForeground(new java.awt.Color(249, 97, 103));
        jLabel_SoLuong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_SoLuong.setText("Số Lượng CN:");
        jLabel_SoLuong.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_TenCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_TenChuCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_DiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Hotline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_SoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_ID)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TenCH)
                .addGap(21, 21, 21)
                .addComponent(jLabel_TenChuCH)
                .addGap(18, 18, 18)
                .addComponent(jLabel_DiaChi)
                .addGap(27, 27, 27)
                .addComponent(jLabel_Hotline)
                .addGap(18, 18, 18)
                .addComponent(jLabel_SoLuong)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_DiaChi;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_Hotline;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_SoLuong;
    private javax.swing.JLabel jLabel_TenCH;
    private javax.swing.JLabel jLabel_TenChuCH;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
