package My_Forms;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;


public class ThongTinChungNhan extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    My_Classes.CuaHang cuahang = new My_Classes.CuaHang();
    My_Classes.ChungNhan chungnhan = new My_Classes.ChungNhan();
    My_Classes.Func_Class func = new My_Classes.Func_Class();

    public ThongTinChungNhan(int id_chungnhan) {
        initComponents();
        this.setLocationRelativeTo(null);

        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(61, 20, 96));
        jPanel1.setBorder(panelHeaderBorder);

        //display image        
        func.displayImage(100, 100, null, "/My_Images/icons8_book_reading_100px.png", jLabel_Form_Title);

        //border the image
        Border JlaBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);


        //add a default image

        //display the book infor
        displayBookInfo(id_chungnhan);
    }

    //creat a func to display the book infor
    public void displayBookInfo(int id_chungnhan) {
        try {
            My_Classes.ChungNhan selectedCN = chungnhan.getCNById(id_chungnhan);

            if (selectedCN != null) {
                jLabel_IDCN.setText("ID Chứng Nhận : "+ Integer.toString(selectedCN.getId()));
                jLabel_TenCN.setText("Tên Chứng Nhận : " +selectedCN.getName());
            } else {

            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinChungNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Form_Title = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_IDCN = new javax.swing.JLabel();
        jLabel_TenCN = new javax.swing.JLabel();

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Image.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Form_Title.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Form_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Form_Title.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Form_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Form_Title.setText("THÔNG TIN CHỨNG NHẬN ATVSTP");
        jLabel_Form_Title.setOpaque(true);

        jLabel_Close.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.setOpaque(true);
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_IDCN.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_IDCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_IDCN.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_IDCN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_IDCN.setText("ID:");
        jLabel_IDCN.setOpaque(true);

        jLabel_TenCN.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_TenCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TenCN.setForeground(new java.awt.Color(0, 153, 153));
        jLabel_TenCN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_TenCN.setText("Tên Chứng Nhận :");
        jLabel_TenCN.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_IDCN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TenCN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Form_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_IDCN)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TenCN)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Form_Title;
    private javax.swing.JLabel jLabel_IDCN;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_TenCN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
